{
  "hash": "47b7704ecad4b1e5471d03a4d24e62db",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Predicción de demanda de bicicletas en Seúl\"\nsubtitle: \"Comparación temporal con tidymodels\"\nauthor: \"Miguelangel Palma Rojas\"\ndate: last-modified\nlang: es\n---\n\n## Objetivo de negocio\n\nLos pronósticos horarios ayudan a posicionar bicicletas antes de los picos. Este notebook muestra el flujo completo: validación, tipado de variables, partición temporal, preprocesamiento, ajuste, métricas finales, importancia y diagnóstico de residuos.\n\n## Cargar paquetes\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(ggplot2)\nlibrary(here)\nlibrary(knitr)\nlibrary(readr)\nlibrary(tibble)\nlibrary(tidymodels)\nlibrary(tidyr)\n```\n:::\n\n\n## Leer y validar el snapshot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbikes <- read_csv(\n  here(\"data\", \"seoul_bike_snapshot.csv\"),\n  show_col_types = FALSE,\n  col_types = cols(date = col_date())\n) |>\n  mutate(\n    weekday = factor(weekday),\n    season = factor(season),\n    holiday = factor(holiday),\n    functioning_day = factor(functioning_day),\n    is_weekend = factor(is_weekend)\n  ) |>\n  arrange(date, hour)\n\nrequired_columns <- c(\n  \"date\", \"rented_bike_count\", \"hour\", \"temperature_c\",\n  \"humidity_pct\", \"wind_speed_ms\", \"visibility_10m\",\n  \"dew_point_c\", \"solar_radiation_mj_m2\", \"rainfall_mm\",\n  \"snowfall_cm\", \"season\", \"holiday\", \"functioning_day\",\n  \"weekday\", \"is_weekend\"\n)\n\nmissing_columns <- setdiff(required_columns, names(bikes))\n\nif (length(missing_columns) > 0) {\n  stop(\n    \"Faltan columnas de bicicletas: \",\n    paste(missing_columns, collapse = \", \")\n  )\n}\n\nstopifnot(\n  !any(bikes$rented_bike_count < 0, na.rm = TRUE),\n  anyDuplicated(bikes[c(\"date\", \"hour\")]) == 0,\n  all(bikes$hour %in% 0:23)\n)\n\nbikes |>\n  summarise(\n    observaciones = n(),\n    primera_fecha = min(date),\n    ultima_fecha = max(date),\n    alquiler_promedio = mean(rented_bike_count),\n    alquiler_maximo = max(rented_bike_count)\n  ) |>\n  kable(digits = 1)\n```\n\n::: {.cell-output-display}\n\n\n| observaciones|primera_fecha |ultima_fecha | alquiler_promedio| alquiler_maximo|\n|-------------:|:-------------|:------------|-----------------:|---------------:|\n|          8760|2017-12-01    |2018-11-30   |             704.6|            3556|\n\n\n:::\n:::\n\n\n## Análisis exploratorio\n\nLa variable objetivo conserva unidades reales. Su distribución asimétrica muestra que las horas de demanda alta son menos frecuentes, pero importantes para la operación.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(bikes, aes(x = rented_bike_count)) +\n  geom_histogram(\n    bins = 40,\n    fill = \"#2A9D8F\",\n    color = \"white\"\n  ) +\n  labs(\n    title = \"La demanda horaria está sesgada hacia la derecha\",\n    x = \"Bicicletas alquiladas\",\n    y = \"Horas\"\n  ) +\n  theme_minimal(base_size = 12) +\n  theme(plot.title = element_text(face = \"bold\"))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/rental-distribution-1.png){fig-alt='Histograma del número horario de bicicletas alquiladas.' width=672}\n:::\n:::\n\n\nLos promedios diarios exponen la estacionalidad y los periodos sin operación.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndaily_demand <- bikes |>\n  group_by(date) |>\n  summarise(\n    average_demand = mean(rented_bike_count),\n    .groups = \"drop\"\n  )\n\nggplot(daily_demand, aes(x = date, y = average_demand)) +\n  geom_line(color = \"#457B9D\", alpha = 0.75) +\n  geom_smooth(\n    se = FALSE,\n    color = \"#E76F51\",\n    linewidth = 0.9\n  ) +\n  labs(\n    title = \"La demanda diaria cambia durante el año\",\n    x = \"Fecha\",\n    y = \"Bicicletas alquiladas en promedio\"\n  ) +\n  theme_minimal(base_size = 12) +\n  theme(plot.title = element_text(face = \"bold\"))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/daily-demand-1.png){fig-alt='Demanda diaria promedio durante el periodo observado.' width=672}\n:::\n:::\n\n\nLas dispersiones muestreadas permiten observar relaciones meteorológicas no lineales antes de introducir el random forest.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nweather_relationships <- bikes |>\n  filter(functioning_day == \"Yes\") |>\n  slice(seq(1, n(), by = 4)) |>\n  select(\n    rented_bike_count,\n    temperature_c,\n    humidity_pct,\n    solar_radiation_mj_m2,\n    rainfall_mm\n  ) |>\n  pivot_longer(\n    cols = -rented_bike_count,\n    names_to = \"predictor\",\n    values_to = \"value\"\n  )\n\nggplot(\n  weather_relationships,\n  aes(x = value, y = rented_bike_count)\n) +\n  geom_point(alpha = 0.2, color = \"#457B9D\") +\n  geom_smooth(se = FALSE, color = \"#E76F51\") +\n  facet_wrap(\n    vars(predictor),\n    scales = \"free_x\",\n    ncol = 2\n  ) +\n  labs(\n    title = \"Las relaciones meteorológicas son no lineales\",\n    x = NULL,\n    y = \"Bicicletas alquiladas\"\n  ) +\n  theme_minimal(base_size = 12) +\n  theme(plot.title = element_text(face = \"bold\"))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/weather-relationships-1.png){fig-alt='Dispersiones facetadas que relacionan demanda con temperatura, humedad, radiación y lluvia.' width=672}\n:::\n:::\n\n\n## Demanda por hora y estación\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhourly_demand <- bikes |>\n  filter(functioning_day == \"Yes\") |>\n  group_by(hour, season) |>\n  summarise(\n    average_demand = mean(rented_bike_count),\n    .groups = \"drop\"\n  )\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(\n  hourly_demand,\n  aes(x = hour, y = average_demand, color = season)\n) +\n  geom_line(linewidth = 1) +\n  scale_color_viridis_d(end = 0.85) +\n  scale_x_continuous(breaks = seq(0, 23, 3)) +\n  labs(\n    title = \"La demanda cambia según la hora y la estación\",\n    x = \"Hora\",\n    y = \"Bicicletas alquiladas en promedio\",\n    color = \"Estación\"\n  ) +\n  theme_minimal(base_size = 12) +\n  theme(\n    plot.title = element_text(face = \"bold\"),\n    legend.position = \"bottom\"\n  )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/hourly-demand-chart-1.png){fig-alt='Líneas de demanda promedio por hora para cada estación.' width=672}\n:::\n:::\n\n\n## Definir datos sin fuga de información\n\nLos cierres se excluyen porque sus ceros representan servicio no disponible. Se eliminan la fecha cruda y el indicador redundante de fin de semana; se conserva el día de la semana.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodeling_data <- bikes |>\n  filter(functioning_day == \"Yes\") |>\n  select(-functioning_day, -is_weekend)\n\nset.seed(2026)\n\nbike_split <- initial_time_split(modeling_data, prop = 0.8)\ntraining_data <- training(bike_split)\ntesting_data <- testing(bike_split)\nresamples <- vfold_cv(training_data, v = 3)\n\ntibble(\n  particion = c(\"Entrenamiento y ajuste\", \"Prueba final\"),\n  observaciones = c(nrow(training_data), nrow(testing_data)),\n  primera_fecha = c(min(training_data$date), min(testing_data$date)),\n  ultima_fecha = c(max(training_data$date), max(testing_data$date))\n) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|particion              | observaciones|primera_fecha |ultima_fecha |\n|:----------------------|-------------:|:-------------|:------------|\n|Entrenamiento y ajuste |          6772|2017-12-01    |2018-09-11   |\n|Prueba final           |          1693|2018-09-11    |2018-11-30   |\n\n\n:::\n:::\n\n\n## Línea base de la media\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbaseline_predictions <- testing_data |>\n  transmute(\n    rented_bike_count,\n    .pred = mean(training_data$rented_bike_count)\n  )\n```\n:::\n\n\n## Receta de preprocesamiento\n\nLa fecha no entra en la fórmula. Los niveles categóricos se tratan antes de crear indicadores, se eliminan columnas sin variación y la normalización se estima solo en cada fold.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbike_recipe <- recipe(\n  rented_bike_count ~\n    hour +\n    temperature_c +\n    humidity_pct +\n    wind_speed_ms +\n    visibility_10m +\n    dew_point_c +\n    solar_radiation_mj_m2 +\n    rainfall_mm +\n    snowfall_cm +\n    season +\n    holiday +\n    weekday,\n  data = training_data\n) |>\n  step_unknown(all_nominal_predictors()) |>\n  step_dummy(all_nominal_predictors(), one_hot = FALSE) |>\n  step_zv(all_predictors()) |>\n  step_normalize(all_numeric_predictors())\n```\n:::\n\n\n## Regresión lineal\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlinear_workflow <- workflow() |>\n  add_recipe(bike_recipe) |>\n  add_model(\n    linear_reg() |>\n      set_engine(\"lm\")\n  )\n\nlinear_fit <- fit(linear_workflow, data = training_data)\n\nlinear_predictions <- bind_cols(\n  testing_data |> select(rented_bike_count),\n  predict(linear_fit, new_data = testing_data)\n)\n```\n:::\n\n\n## Elastic Net\n\n\n::: {.cell}\n\n```{.r .cell-code}\nelastic_workflow <- workflow() |>\n  add_recipe(bike_recipe) |>\n  add_model(\n    linear_reg(\n      penalty = tune(),\n      mixture = tune()\n    ) |>\n      set_engine(\"glmnet\")\n  )\n\nelastic_grid <- grid_space_filling(\n  penalty(range = c(-5, 1)),\n  mixture(),\n  size = 6\n)\n\nelastic_results <- tune_grid(\n  elastic_workflow,\n  resamples = resamples,\n  grid = elastic_grid,\n  metrics = metric_set(rmse, mae, rsq_trad)\n)\n\nbest_elastic <- select_best(elastic_results, metric = \"rmse\")\nbest_elastic |> kable(digits = 5)\n```\n\n::: {.cell-output-display}\n\n\n| penalty| mixture|.config         |\n|-------:|-------:|:---------------|\n| 0.00016|       1|pre0_mod2_post0 |\n\n\n:::\n\n```{.r .cell-code}\nelastic_fit <- elastic_workflow |>\n  finalize_workflow(best_elastic) |>\n  fit(data = training_data)\n\nelastic_predictions <- bind_cols(\n  testing_data |> select(rented_bike_count),\n  predict(elastic_fit, new_data = testing_data)\n)\n```\n:::\n\n\n## Random forest\n\n\n::: {.cell}\n\n```{.r .cell-code}\nforest_workflow <- workflow() |>\n  add_recipe(bike_recipe) |>\n  add_model(\n    rand_forest(\n      mtry = tune(),\n      min_n = tune(),\n      trees = 300\n    ) |>\n      set_engine(\"ranger\", importance = \"permutation\") |>\n      set_mode(\"regression\")\n  )\n\nforest_grid <- grid_space_filling(\n  mtry(range = c(3L, 12L)),\n  min_n(range = c(5L, 35L)),\n  size = 6\n)\n\nforest_results <- tune_grid(\n  forest_workflow,\n  resamples = resamples,\n  grid = forest_grid,\n  metrics = metric_set(rmse, mae, rsq_trad)\n)\n\nbest_forest <- select_best(forest_results, metric = \"rmse\")\nbest_forest |> kable()\n```\n\n::: {.cell-output-display}\n\n\n| mtry| min_n|.config         |\n|----:|-----:|:---------------|\n|   10|    11|pre0_mod5_post0 |\n\n\n:::\n\n```{.r .cell-code}\nforest_fit <- forest_workflow |>\n  finalize_workflow(best_forest) |>\n  fit(data = training_data)\n\nforest_predictions <- bind_cols(\n  testing_data |> select(rented_bike_count),\n  predict(forest_fit, new_data = testing_data)\n)\n```\n:::\n\n\nLa superficie de ajuste muestra cómo la complejidad de los árboles y el tamaño mínimo de nodo afectan el error de validación.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nforest_tuning <- forest_results |>\n  collect_metrics() |>\n  filter(.metric == \"rmse\")\n\nggplot(\n  forest_tuning,\n  aes(\n    x = mtry,\n    y = min_n,\n    color = mean,\n    size = mean\n  )\n) +\n  geom_point(alpha = 0.9) +\n  scale_color_viridis_c(\n    option = \"C\",\n    direction = -1\n  ) +\n  scale_size(\n    range = c(3, 7),\n    guide = \"none\"\n  ) +\n  labs(\n    title = \"Superficie de ajuste del random forest\",\n    subtitle = \"Un RMSE menor indica mejor resultado de validación\",\n    x = \"Predictores evaluados por división (mtry)\",\n    y = \"Observaciones mínimas por nodo\",\n    color = \"RMSE\"\n  ) +\n  theme_minimal(base_size = 12) +\n  theme(plot.title = element_text(face = \"bold\"))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/forest-tuning-1.png){fig-alt='Combinaciones de ajuste del random forest coloreadas por RMSE de validación.' width=672}\n:::\n:::\n\n\n## Rendimiento en la prueba final\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbaseline_metrics <- bind_rows(\n  rmse(baseline_predictions, rented_bike_count, .pred),\n  mae(baseline_predictions, rented_bike_count, .pred),\n  rsq_trad(baseline_predictions, rented_bike_count, .pred)\n) |>\n  mutate(model = \"Línea base\")\n\nlinear_metrics <- bind_rows(\n  rmse(linear_predictions, rented_bike_count, .pred),\n  mae(linear_predictions, rented_bike_count, .pred),\n  rsq_trad(linear_predictions, rented_bike_count, .pred)\n) |>\n  mutate(model = \"Regresión lineal\")\n\nelastic_metrics <- bind_rows(\n  rmse(elastic_predictions, rented_bike_count, .pred),\n  mae(elastic_predictions, rented_bike_count, .pred),\n  rsq_trad(elastic_predictions, rented_bike_count, .pred)\n) |>\n  mutate(model = \"Elastic Net\")\n\nforest_metrics <- bind_rows(\n  rmse(forest_predictions, rented_bike_count, .pred),\n  mae(forest_predictions, rented_bike_count, .pred),\n  rsq_trad(forest_predictions, rented_bike_count, .pred)\n) |>\n  mutate(model = \"Random forest\")\n\nholdout_metrics <- bind_rows(\n  baseline_metrics,\n  linear_metrics,\n  elastic_metrics,\n  forest_metrics\n) |>\n  select(model, .metric, .estimate)\n\nmetrics_table <- holdout_metrics |>\n  pivot_wider(\n    names_from = .metric,\n    values_from = .estimate\n  ) |>\n  arrange(rmse)\n\nmetrics_table |>\n  kable(digits = 2)\n```\n\n::: {.cell-output-display}\n\n\n|model            |   rmse|    mae| rsq_trad|\n|:----------------|------:|------:|--------:|\n|Random forest    | 348.17| 246.34|     0.66|\n|Regresión lineal | 432.95| 319.56|     0.48|\n|Elastic Net      | 433.05| 317.66|     0.48|\n|Línea base       | 634.41| 491.51|    -0.12|\n\n\n:::\n:::\n\n\nRMSE y MAE se mantienen interpretables como bicicletas alquiladas.\n\n## Observado frente a predicho\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprediction_comparison <- bind_rows(\n  baseline_predictions |>\n    mutate(model = \"Línea base\"),\n  linear_predictions |>\n    mutate(model = \"Regresión lineal\"),\n  elastic_predictions |>\n    mutate(model = \"Elastic Net\"),\n  forest_predictions |>\n    mutate(model = \"Random forest\")\n) |>\n  mutate(\n    model = factor(\n      model,\n      levels = c(\n        \"Línea base\",\n        \"Regresión lineal\",\n        \"Elastic Net\",\n        \"Random forest\"\n      )\n    )\n  )\n\nggplot(\n  prediction_comparison,\n  aes(x = rented_bike_count, y = .pred)\n) +\n  geom_abline(\n    slope = 1,\n    intercept = 0,\n    color = \"#E76F51\",\n    linewidth = 0.8\n  ) +\n  geom_point(alpha = 0.25, color = \"#2A9D8F\") +\n  facet_wrap(vars(model), ncol = 2) +\n  coord_equal() +\n  labs(\n    title = \"Demanda observada y predicha en horas futuras no vistas\",\n    x = \"Bicicletas observadas\",\n    y = \"Bicicletas predichas\"\n  ) +\n  theme_minimal(base_size = 12) +\n  theme(plot.title = element_text(face = \"bold\"))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/observed-predicted-1.png){fig-alt='Gráficos facetados de valores observados y predichos para cuatro modelos.' width=672}\n:::\n:::\n\n\n## Importancia de variables\n\n\n::: {.cell}\n\n```{.r .cell-code}\nforest_engine <- extract_fit_engine(forest_fit)\n\nvariable_importance <- enframe(\n  forest_engine$variable.importance,\n  name = \"variable\",\n  value = \"importance\"\n) |>\n  arrange(desc(importance)) |>\n  slice_head(n = 12)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(\n  variable_importance,\n  aes(x = importance, y = reorder(variable, importance))\n) +\n  geom_col(fill = \"#2A9D8F\") +\n  labs(\n    title = \"Importancia por permutación del random forest\",\n    x = \"Importancia\",\n    y = NULL\n  ) +\n  theme_minimal(base_size = 12) +\n  theme(\n    plot.title = element_text(face = \"bold\"),\n    panel.grid.major.y = element_blank()\n  )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/variable-importance-chart-1.png){fig-alt='Barras horizontales con las variables más importantes del random forest.' width=672}\n:::\n:::\n\n\n## Diagnóstico de residuos\n\n\n::: {.cell}\n\n```{.r .cell-code}\nforest_diagnostics <- forest_predictions |>\n  mutate(residual = rented_bike_count - .pred)\n\nggplot(forest_diagnostics, aes(x = .pred, y = residual)) +\n  geom_hline(yintercept = 0, color = \"#555555\") +\n  geom_point(alpha = 0.35, color = \"#2A9D8F\") +\n  geom_smooth(se = FALSE, color = \"#E76F51\") +\n  labs(\n    title = \"Residuos del random forest en observaciones no vistas\",\n    x = \"Bicicletas predichas\",\n    y = \"Observado menos predicho\"\n  ) +\n  theme_minimal(base_size = 12) +\n  theme(plot.title = element_text(face = \"bold\"))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/residual-chart-1.png){fig-alt='Residuos frente a predicciones del random forest en la prueba final.' width=672}\n:::\n:::\n\n\n## Conclusión\n\n- El random forest es el mejor modelo final, con RMSE de 348.17, MAE de 246.34 y R² de 0.66.\n- Frente a la línea base reduce el RMSE en 45.1% y el MAE en 49.9%.\n- El bosque seleccionado utiliza un valor `mtry` de 10 y un valor `min_n` de 11; Elastic Net se comporta como lasso (`mixture` = 1) con penalización 1.58e-04.\n- Las variables líderes por importancia de permutación son hour, temperature_c, solar_radiation_mj_m2, humidity_pct, dew_point_c, lo que confirma que la hora y los efectos meteorológicos no lineales concentran la capacidad predictiva.\n- La dispersión de residuos aumenta en periodos de alta demanda. El modelo funciona como referencia para planeación urbana, pero necesita calibración de picos, reentrenamiento continuo y variables por estación para uso operativo.\n\nConsulta la [versión en inglés](../index.qmd).\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}